# Macro file for example B1
# 
# Can be run in batch, without graphic
# or interactively: Idle> /control/execute run1.mac
#
# Change the default number of workers (in multi-threading mode) 
#/run/numberOfWorkers 4
#
# Initialize kernel
/control/execute physics.mac
/run/initialize
/control/execute primary2.mac
#
/control/verbose 0
/run/verbose 0
/event/verbose 0
/tracking/verbose 0
#
/run/beamOn 10
